export const movies=[
    {
        id:1,
        title:"The Shawshank Redemption",
        year:1994,
        genre:"Drama",
        rating:9.3,
        image:"https://m.media-amazon.com/images/M/MV5BODU5YjY2ZTAtM2Y1Ny00ZGE0LWI5NmItZTIzM2I3ZTAxOTYwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    },
    {
        id:2,
        title:"The Godfather",
        year:1972,
        genre:["Crime", "Drama"],
        rating:9.2,
        image:"https://m.media-amazon.com/images/M/MV5BNzA4YjE3ZmItMjc0NC00N2E1LTg3ZjAtN2QzZGM4NTJmNjc4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    },
    {
        id:3,
        title:"The Dark Knight",
        year:2008,
        genre:["Action", "Crime", "Drama"],
        rating:9.0,
        image:"https://m.media-amazon.com/images/M/MV5BMTc4MjA0NTYyOF5BMl5BanBnXkFtZTcwOTg3MDY0MQ@@._V1_.jpg",
    },
    {
        id:4,
        title:"Pulp Fiction",
        year:1994,
        genre:["Crime", "Drama"],
        rating:8.9,
        image:"https://m.media-amazon.com/images/M/MV5BMTc0MjY4NTI1NF5BMl5BanBnXkFtZTcwNjY3MDY0MQ@@._V1_.jpg",
    },
    {
        id:5,
        title:"The Lord of the Rings: The Return of the King",
        year:2003,
        genre:["Action", "Adventure", "Drama"],
        rating:8.9,
        image:"https://m.media-amazon.com/images/M/MV5BMTY0NTc3NzY4OF5BMl5BanBnXkFtZTcwNTI3MDY0MQ@@._V1_.jpg",
    },
    {
        id:6,
        title:"Forrest Gump",
        year:1994,
        genre:["Drama", "Romance"],
        rating:8.8,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:7,
        title:"Inception",
        year:2010,
        genre:["Action", "Adventure", "Sci-Fi"],
        rating:8.8,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:8,
        title:"The Matrix",
        year:1999,
        genre:["Action", "Sci-Fi"],
        rating:8.7,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:9,
        title:"Goodfellas",
        year:1990,
        genre:["Biography", "Crime", "Drama"],
        rating:8.7,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:10,
        title:"Fight Club",
        year:1999,
        genre:["Drama"],
        rating:8.8,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:11,
        title:"The Lord of the Rings: The Fellowship of the Ring",
        year:2001,
        genre:["Action", "Adventure", "Drama"],
        rating:8.8,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:12,
        title:"The Empire Strikes Back",
        year:1980,
        genre:["Action", "Adventure", "Fantasy"],
        rating:8.7,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:13,
        title:"The Social Network",
        year:2010,
        genre:["Biography", "Drama"],
        rating:7.7,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:14,
        title:"The Silence of the Lambs",
        year:1991,
        genre:["Crime", "Drama", "Thriller"],
        rating:8.6,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:15,
        title:"Se7en",
        year:1995,
        genre:["Crime", "Drama", "Mystery"],
        rating:8.6,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    }
    ,
    {
        id:16,
        title:"The Usual Suspects",
        year:1995,
        genre:["Crime", "Drama", "Mystery"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:17,
        title:"The Lion King",
        year:1994,
        genre:["Animation", "Adventure", "Drama"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:18,
        title:"Back to the Future",
        year:1985,
        genre:["Adventure", "Comedy", "Sci-Fi"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:19,
        title:"The Prestige",
        year:2006,
        genre:["Drama", "Mystery", "Sci-Fi"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:20,
        title:"The Departed",
        year:2006,
        genre:["Crime", "Drama", "Thriller"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:21,
        title:"Whiplash",
        year:2014,
        genre:["Drama", "Music"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:22,
        title:"Gladiator",
        year:2000,
        genre:["Action", "Adventure", "Drama"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:23,
        title:"The Intouchables",
        year:2011,
        genre:["Biography", "Comedy", "Drama"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:24,
        title:"The Green Mile",
        year:1999,
        genre:["Crime", "Drama", "Fantasy"],
        rating:8.6,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:25,
        title:"Interstellar",
        year:2014,
        genre:["Adventure", "Drama", "Sci-Fi"],
        rating:8.6,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    }
    ,
    {
        id:26,
        title:"City of God",
        year:2002,
        genre:["Crime", "Drama"],
        rating:8.6,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:27,
        title:"The Pianist",
        year:2002,
        genre:["Biography", "Drama", "Music"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:28,
        title:"Terminator 2: Judgment Day",
        year:1991,
        genre:["Action", "Sci-Fi"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:29,
        title:"The Great Dictator",
        year:1940,
        genre:["Comedy", "Drama", "War"],
        rating:8.4,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:30,
        title:"The Lives of Others",
        year:2006,
        genre:["Drama", "Thriller"],
        rating:8.4,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:31,
        title:"Grave of the Fireflies",
        year:1988,
        genre:["Animation", "Drama", "War"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:32,
        title:"The Shining",
        year:1980,
        genre:["Drama", "Horror"],
        rating:8.4,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:33,
        title:"American History X",
        year:1998,
        genre:["Crime", "Drama"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:34,
        title:"The Dark Knight Rises",
        year:2012,
        genre:["Action", "Adventure"],
        rating:8.4,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:35,
        title:"The Green Book",
        year:2018,
        genre:["Biography", "Comedy", "Drama"],
        rating:8.6,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    }
    ,
    {
        id:36,
        title:"The Lion King",
        year:1994,
        genre:["Animation", "Adventure", "Drama"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:37,
        title:"The Wolf of Wall Street",
        year:2013,
        genre:["Biography", "Comedy", "Crime"],
        rating:8.2,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:38,
        title:"The Silence of the Lambs",
        year:1991,
        genre:["Crime", "Drama", "Thriller"],
        rating:8.6,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:39,
        title:"The Departed",
        year:2006,
        genre:["Crime", "Drama", "Thriller"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:40,
        title:"The Intouchables",
        year:2011,
        genre:["Biography", "Comedy", "Drama"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    }
    ,
    {
        id:41,
        title:"The Great Dictator",
        year:1940,
        genre:["Comedy", "Drama", "War"],
        rating:8.4,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:42,
        title:"The Lives of Others",
        year:2006,
        genre:["Drama", "Thriller"],
        rating:8.4,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:43,
        title:"Grave of the Fireflies",
        year:1988,
        genre:["Animation", "Drama", "War"],
        rating:8.5,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
    {
        id:44,
        title:"The Shining",
        year:1980,
        genre:["Drama", "Horror"],
        rating:8.4,
        image:"https://m.media-amazon.com/images/M/MV5BMTk2MjA1OTg4N15BMl5BanBnXkFtZTgwNjQzMDY0MQ@@._V1_.jpg",
    },
]